#ifndef QTCOMMON2_GLOBAL_H
#define QTCOMMON2_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTCOMMON2_LIBRARY)
#  define QTCOMMON2SHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTCOMMON2SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCOMMON2_GLOBAL_H
